repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
      - --rcfile=.pylintrc
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
